### ISSUE TITLE
查看大图功能接口

### ISSUE THREAD

**Issue by IrvingW** [SE-Project-Group/Backend#10]
名称：getBigPhotoUrls
参数：feed_id
是否需要验证：不需要
成功返回：结果返回一个大的String，每个url之间以“，”分隔
失败返回：“failed”
restful：feedRestful

名称：getBigPortraitUrl
参数：user_id
是否需要验证：不需要
成功返回：url （String）
失败返回：“failed”
restful：userRestful

以上两个接口都可以直接调用我写好的signedUrlFactory类里的同名方法

**Comment by sjtuXZT** [comment]
ok
