### ISSUE TITLE
修改getFollowingFeedList

### ISSUE THREAD

**Issue by IrvingW** [SE-Project-Group/Backend#19]
将该接口修改为getFollowingFeedsBeforeTime
类似于getPublicFeedsBeforeTime返回在某个时间点之前的最靠前的十条动态（注意顺序要由近到远，也就是和数据库中的顺序是相反的）
需要验证
返回ReturnFeed的列表

**Comment by IrvingW** [comment]
忘记了，还有一个getFollowingFeedsAfterTime
这两个接口的参数都是 String time和 int user_id

**Comment by sjtuXZT** [comment]
ok
