### ISSUE TITLE
评论推送功能修改

### ISSUE THREAD

**Issue by IrvingW** [SE-Project-Group/Backend#26]
1.在自己的动态下面评论不需要JMessage通知自己
2.A评论了B发在C的动态下面的评论，需要通知B而不是通知C，也就是评论动态和评论评论需要判断一下分别处理

**Comment by IrvingW** [comment]
另外我看你们的代码注释蛮少的，尽量多写点注释吧

**Comment by Katnisszmx** [comment]
done
