### ISSUE TITLE
getFollowingFeedList 接口出错

### ISSUE THREAD

**Issue by IrvingW** [SE-Project-Group/Backend#8]
服务器链接是：
http://106.15.188.135:8080/track/rest/app/feed/getFollowingFeedList?user_id=10000&sign=QI8DhhwoeMPvUFIu0wsc7g%3D%3D
GET方法

**Comment by Katnisszmx** [comment]
这个还需要一个time参数，表示你需要哪个时间之前的动态。建议初始值为为当前时间
